stages:
  - test
  - stats
  - deploy
  - release

default:
  image: namboy94/ci-docker-environment:0.1.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  script:
    - python-unittest

deploy_develop:
  stage: deploy
  only: [develop]
  tags: [hk-tippspiel-develop]
  before_script:
    - python3 -m venv virtual
    - source virtual/bin/activate
    - pip install ci-scripts
  script:
    - export TIPPSPIEL_ENV=develop
    - deploy-flask $BUNDESLIGA_TIPPSPIEL_DEVELOP_HOME

deploy_production:
  stage: deploy
  only: [master]
  tags: [hk-tippspiel]
  before_script:
    - python3 -m venv virtual
    - source virtual/bin/activate
    - pip install ci-scripts
  script:
    - export TIPPSPIEL_ENV=production
    - deploy-flask $BUNDESLIGA_TIPPSPIEL_HOME

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - sphinx-docgen
