stages:
  - deploy

deploy_page:
  stage: deploy
  tags:
    - linux-buildserver
  only:
    - master
  script:
    - rsync -av web/ /var/www/tippspiel.krumreyh.com/public_html --delete-after
    - rsync -av scripts/ /var/www/tippspiel.krumreyh.com/scripts --delete-after

deploy_demo_page:
  stage: deploy
  tags:
    - linux-buildserver
  only:
    - develop
  script:
    - rsync -av web/ /var/www/demo.tippspiel.krumreyh.com/public_html --delete-after

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - buildserver_linux
  script:
    - git clone https://gitlab.namibsun.net/namboy94/gitlab-release-uploader.git
    - git clone https://gitlab.namibsun.net/namboy94/changelog-reader.git
    - python changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python gitlab-release-uploader/gitlab-release-uploader.py namboy94 toktokkie $GITLAB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master -u https://gitlab.namibsun.net