stages:
  - mirror
  - test
  - release
  - deploy

variables:
  PRODUCTION: "1"  # Tells script that it's running on the production instance

lint:
  stage: test
  tags:
    - php
    - composer
  script:
    - composer update
    - php vendor/phpcheckstyle/phpcheckstyle/run.php --src src --src test --config checkstyle.xml

unittest:
  stage: test
  tags:
    - composer
    - php
    - progstats
    - bundesliga-tippspiel-test-db
  script:
    - composer update
    - echo $TEST_DB_PASS > DB_PASS.secret
    - vendor/bin/phpunit test --coverage-html=coverage --stderr
    - rsync -av coverage/ /var/www/progstats.namibsun.net/public/coverage/bundesliga-tippspiel --delete-before
    - rm DB_PASS.secret

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python ci-scripts/src/github-release-uploader/github-release-uploader.py namboy94 bundesliga-tippspiel $GITHUB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/src/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python ci-scripts/src/gitlab-release-uploader/gitlab-release-uploader.py namboy94 bundesliga-tippspiel $GITLAB_ACCESS_TOKEN
      $(cat version) current_changelog artifacts -b master -u https://gitlab.namibsun.net

deploy_develop_webpage:
  stage: deploy
  only:
    - master
    - develop
  tags:
    - bundesliga-tippspiel-develop
  script:
    - echo $DB_PASS > DB_PASS.secret
    - echo $RECAPTCHA_SITE_KEY > RECAPTCHA_SITE_KEY.secret
    - echo $KUDUBOT_WHATSAPP_CONFIG > kudubot/connection_config/whatsapp.conf
    - echo $KUDUBOT_TELEGRAM_CONFIG > kudubot/connection_config/telegram.conf
    - echo "domain = \"develop.hk-tippspiel.com\"" > kudubot/modules/bundesliga_tippspiel_reminder/__init__.py
    - composer update
    -

deploy_live_webpage:
  stage: deploy
  only:
    - master
  tags:
    - bundesliga-tippspiel-live
  script:
    - export LIVE=1
    - ./deploy.sh
