stages:
  - deploy

deploy_page:
  stage: deploy
  tags:
    - linux-buildserver
  only:
    - master
  script:
    - rsync -av web/ /var/www/tippspiel.krumreyh.com/public_html --delete-after
    - rsync -av scripts/ /var/www/tippspiel.krumreyh.com/scripts --delete-after

deploy_demo_page:
  stage: deploy
  tags:
    - linux-buildserver
  only:
    - develop
  script:
    - rsync -av web/ /var/www/demo.tippspiel.krumreyh.com/public_html --delete-after
