stages:
  - deploy

deploy_page:
  stage: deploy
  only:
    - master
  script:
    - rsync -av web/ /var/www/tippspiel.krumreyh.com/public_html --delete-after

deploy_demo_page:
  stage: deploy
  only:
    - develop
  script:
    - rsync -av web/ /var/www/demo.tippspiel.krumreyh.com/public_html
      --delete-after
