version: "3.2"
networks:
  net:
    driver: bridge
services:
  app:
    build: .
    image: "bundesliga-tippspiel"
    container_name: "bundesliga-tippspiel-app"
    depends_on:
      - db
    networks:
      - net
    volumes:
      - logs:/var/logs
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file: .env
    environment:
      - DB_MODE=postgresql
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - LOGGING_PATH=/var/logs/bundesliga_tippspiel.log
      - DEBUG_LOGGING_PATH=/var/logs/bundesliga_tippspiel_debug.log
    restart: always
  db:
    image: postgres:13
    container_name: "bundesliga-tippspiel-db"
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - data:/var/lib/postgresql/data
      - /home/hermann/git/bundesliga-tippspiel/data:/data
    restart: always
volumes:
  logs: ~
  data: ~
